services:
  chatbot-backend:
    build:
      context: .
      dockerfile: Dockerfile.chatbot-backend
    image: elopezcastaneda5061/queueiq-chatbot-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  chatbot-frontend:
    build:
      context: .
      dockerfile: Dockerfile.chatbot-frontend
    image: elopezcastaneda5061/queueiq-chatbot-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - chatbot-backend
    restart: unless-stopped

  queuecontrol-simulator:
    build:
      context: .
      dockerfile: Dockerfile.queuecontrol-dashboard
    image: elopezcastaneda5061/queueiq-queuecontrol-dashboard:latest
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped

  web:
    build: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}